### ISSUE TITLE
Avoid logs in console

### ISSUE THREAD

**Issue by Progyan1997** [MarkRabey/material-modal#5]
This module contains a ton of clickEventHandlers inside modal which are good for development purpose but not good for shipping. How can I disable that?

**Comment by MarkRabey** [comment]
@Progyan1997 I will at some point. I honestly haven't done any development on this repo in a very long time. Hoping to get back at it soon though.

**Comment by MarkRabey** [comment]
`console.log` removed with Pull Request #8.
